# Configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - misspell

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # We don't need strict struct field alignment optimizations
  gosec:
    # To run all rules of gosec
    severity: "low"
    confidence: "low"
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
